"""add payment_mode and fx fields to subscription and bill_payment

Revision ID: 2232f5dfe6f0
Revises: ea66ca106eb4
Create Date: 2026-03-19 13:38:56.848277

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2232f5dfe6f0'
down_revision: str | Sequence[str] | None = 'ea66ca106eb4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_payment', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.add_column('bill_payment', sa.Column('paid_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('bill_payment', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('bill_payment', sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('subscription', sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'payment_mode')
    op.drop_column('bill_payment', 'payment_mode')
    op.drop_column('bill_payment', 'exchange_rate')
    op.drop_column('bill_payment', 'paid_currency')
    op.drop_column('bill_payment', 'paid_amount')
    # ### end Alembic commands ###
