"""add note and task tables

Revision ID: ea66ca106eb4
Revises: 99fc15ee5194
Create Date: 2026-03-19 12:55:26.498523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea66ca106eb4'
down_revision: Union[str, Sequence[str], None] = '99fc15ee5194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_owner_id'), 'task', ['owner_id'], unique=False)
    op.create_table('note_tag',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'term_id')
    )
    op.create_table('task_tag',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'term_id')
    )
    op.drop_constraint(op.f('country_alpha2_key'), 'country', type_='unique')
    op.drop_constraint(op.f('country_alpha3_key'), 'country', type_='unique')
    op.drop_index(op.f('ix_country_alpha2'), table_name='country')
    op.create_index(op.f('ix_country_alpha2'), 'country', ['alpha2'], unique=True)
    op.drop_index(op.f('ix_country_alpha3'), table_name='country')
    op.create_index(op.f('ix_country_alpha3'), 'country', ['alpha3'], unique=True)
    op.drop_constraint(op.f('language_iso_639_1_key'), 'language', type_='unique')
    op.drop_constraint(op.f('language_iso_639_2_key'), 'language', type_='unique')
    op.drop_index(op.f('ix_language_iso_639_1'), table_name='language')
    op.create_index(op.f('ix_language_iso_639_1'), 'language', ['iso_639_1'], unique=True)
    op.drop_index(op.f('ix_language_iso_639_2'), table_name='language')
    op.create_index(op.f('ix_language_iso_639_2'), 'language', ['iso_639_2'], unique=True)
    op.drop_constraint(op.f('person_context_person_id_key'), 'person_context', type_='unique')
    op.drop_index(op.f('ix_person_context_person_id'), table_name='person_context')
    op.create_index(op.f('ix_person_context_person_id'), 'person_context', ['person_id'], unique=True)
    op.drop_constraint(op.f('person_location_person_id_key'), 'person_location', type_='unique')
    op.drop_index(op.f('ix_person_location_person_id'), table_name='person_location')
    op.create_index(op.f('ix_person_location_person_id'), 'person_location', ['person_id'], unique=True)
    op.drop_constraint(op.f('person_professional_person_id_key'), 'person_professional', type_='unique')
    op.drop_index(op.f('ix_person_professional_person_id'), table_name='person_professional')
    op.create_index(op.f('ix_person_professional_person_id'), 'person_professional', ['person_id'], unique=True)
    op.drop_constraint(op.f('person_profile_person_id_key'), 'person_profile', type_='unique')
    op.drop_index(op.f('ix_person_profile_person_id'), table_name='person_profile')
    op.create_index(op.f('ix_person_profile_person_id'), 'person_profile', ['person_id'], unique=True)
    op.drop_constraint(op.f('person_social_person_id_key'), 'person_social', type_='unique')
    op.drop_index(op.f('ix_person_social_person_id'), table_name='person_social')
    op.create_index(op.f('ix_person_social_person_id'), 'person_social', ['person_id'], unique=True)
    op.drop_constraint(op.f('timezone_name_key'), 'timezone', type_='unique')
    op.drop_index(op.f('ix_timezone_name'), table_name='timezone')
    op.create_index(op.f('ix_timezone_name'), 'timezone', ['name'], unique=True)
    op.drop_constraint(op.f('vocabulary_machine_name_key'), 'vocabulary', type_='unique')
    op.drop_index(op.f('ix_vocabulary_machine_name'), table_name='vocabulary')
    op.create_index(op.f('ix_vocabulary_machine_name'), 'vocabulary', ['machine_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_machine_name'), table_name='vocabulary')
    op.create_index(op.f('ix_vocabulary_machine_name'), 'vocabulary', ['machine_name'], unique=False)
    op.create_unique_constraint(op.f('vocabulary_machine_name_key'), 'vocabulary', ['machine_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_timezone_name'), table_name='timezone')
    op.create_index(op.f('ix_timezone_name'), 'timezone', ['name'], unique=False)
    op.create_unique_constraint(op.f('timezone_name_key'), 'timezone', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_person_social_person_id'), table_name='person_social')
    op.create_index(op.f('ix_person_social_person_id'), 'person_social', ['person_id'], unique=False)
    op.create_unique_constraint(op.f('person_social_person_id_key'), 'person_social', ['person_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_person_profile_person_id'), table_name='person_profile')
    op.create_index(op.f('ix_person_profile_person_id'), 'person_profile', ['person_id'], unique=False)
    op.create_unique_constraint(op.f('person_profile_person_id_key'), 'person_profile', ['person_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_person_professional_person_id'), table_name='person_professional')
    op.create_index(op.f('ix_person_professional_person_id'), 'person_professional', ['person_id'], unique=False)
    op.create_unique_constraint(op.f('person_professional_person_id_key'), 'person_professional', ['person_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_person_location_person_id'), table_name='person_location')
    op.create_index(op.f('ix_person_location_person_id'), 'person_location', ['person_id'], unique=False)
    op.create_unique_constraint(op.f('person_location_person_id_key'), 'person_location', ['person_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_person_context_person_id'), table_name='person_context')
    op.create_index(op.f('ix_person_context_person_id'), 'person_context', ['person_id'], unique=False)
    op.create_unique_constraint(op.f('person_context_person_id_key'), 'person_context', ['person_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_language_iso_639_2'), table_name='language')
    op.create_index(op.f('ix_language_iso_639_2'), 'language', ['iso_639_2'], unique=False)
    op.drop_index(op.f('ix_language_iso_639_1'), table_name='language')
    op.create_index(op.f('ix_language_iso_639_1'), 'language', ['iso_639_1'], unique=False)
    op.create_unique_constraint(op.f('language_iso_639_2_key'), 'language', ['iso_639_2'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('language_iso_639_1_key'), 'language', ['iso_639_1'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_country_alpha3'), table_name='country')
    op.create_index(op.f('ix_country_alpha3'), 'country', ['alpha3'], unique=False)
    op.drop_index(op.f('ix_country_alpha2'), table_name='country')
    op.create_index(op.f('ix_country_alpha2'), 'country', ['alpha2'], unique=False)
    op.create_unique_constraint(op.f('country_alpha3_key'), 'country', ['alpha3'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('country_alpha2_key'), 'country', ['alpha2'], postgresql_nulls_not_distinct=False)
    op.drop_table('task_tag')
    op.drop_table('note_tag')
    op.drop_index(op.f('ix_task_owner_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
