"""Seed all reference data: ISO countries, languages, timezones, and vocabularies.

Usage:
    python -m seeds.seed_data
"""
# ruff: noqa: E501

import asyncio
import uuid

from sqlalchemy.ext.asyncio import AsyncSession
from sqlmodel import select

from app.models.iso_reference import Country, Language, Timezone
from app.models.vocabulary import Term, Vocabulary

# ── ISO Seed Data ──────────────────────────────────────────────────────────────

_COUNTRIES = [
    {
        "name": "Afghanistan",
        "alpha2": "AF",
        "alpha3": "AFG",
        "numeric": "004",
        "calling_code": "+93",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇦🇫",
    },
    {
        "name": "Albania",
        "alpha2": "AL",
        "alpha3": "ALB",
        "numeric": "008",
        "calling_code": "+355",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇦🇱",
    },
    {
        "name": "Algeria",
        "alpha2": "DZ",
        "alpha3": "DZA",
        "numeric": "012",
        "calling_code": "+213",
        "region": "Africa",
        "subregion": "Northern Africa",
        "flag_emoji": "🇩🇿",
    },
    {
        "name": "Argentina",
        "alpha2": "AR",
        "alpha3": "ARG",
        "numeric": "032",
        "calling_code": "+54",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇦🇷",
    },
    {
        "name": "Armenia",
        "alpha2": "AM",
        "alpha3": "ARM",
        "numeric": "051",
        "calling_code": "+374",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇦🇲",
    },
    {
        "name": "Australia",
        "alpha2": "AU",
        "alpha3": "AUS",
        "numeric": "036",
        "calling_code": "+61",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "flag_emoji": "🇦🇺",
    },
    {
        "name": "Austria",
        "alpha2": "AT",
        "alpha3": "AUT",
        "numeric": "040",
        "calling_code": "+43",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇦🇹",
    },
    {
        "name": "Azerbaijan",
        "alpha2": "AZ",
        "alpha3": "AZE",
        "numeric": "031",
        "calling_code": "+994",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇦🇿",
    },
    {
        "name": "Bangladesh",
        "alpha2": "BD",
        "alpha3": "BGD",
        "numeric": "050",
        "calling_code": "+880",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇧🇩",
    },
    {
        "name": "Belarus",
        "alpha2": "BY",
        "alpha3": "BLR",
        "numeric": "112",
        "calling_code": "+375",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇧🇾",
    },
    {
        "name": "Belgium",
        "alpha2": "BE",
        "alpha3": "BEL",
        "numeric": "056",
        "calling_code": "+32",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇧🇪",
    },
    {
        "name": "Bolivia",
        "alpha2": "BO",
        "alpha3": "BOL",
        "numeric": "068",
        "calling_code": "+591",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇧🇴",
    },
    {
        "name": "Bosnia and Herzegovina",
        "alpha2": "BA",
        "alpha3": "BIH",
        "numeric": "070",
        "calling_code": "+387",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇧🇦",
    },
    {
        "name": "Brazil",
        "alpha2": "BR",
        "alpha3": "BRA",
        "numeric": "076",
        "calling_code": "+55",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇧🇷",
    },
    {
        "name": "Bulgaria",
        "alpha2": "BG",
        "alpha3": "BGR",
        "numeric": "100",
        "calling_code": "+359",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇧🇬",
    },
    {
        "name": "Cambodia",
        "alpha2": "KH",
        "alpha3": "KHM",
        "numeric": "116",
        "calling_code": "+855",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇰🇭",
    },
    {
        "name": "Cameroon",
        "alpha2": "CM",
        "alpha3": "CMR",
        "numeric": "120",
        "calling_code": "+237",
        "region": "Africa",
        "subregion": "Middle Africa",
        "flag_emoji": "🇨🇲",
    },
    {
        "name": "Canada",
        "alpha2": "CA",
        "alpha3": "CAN",
        "numeric": "124",
        "calling_code": "+1",
        "region": "Americas",
        "subregion": "Northern America",
        "flag_emoji": "🇨🇦",
    },
    {
        "name": "Chile",
        "alpha2": "CL",
        "alpha3": "CHL",
        "numeric": "152",
        "calling_code": "+56",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇨🇱",
    },
    {
        "name": "China",
        "alpha2": "CN",
        "alpha3": "CHN",
        "numeric": "156",
        "calling_code": "+86",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "flag_emoji": "🇨🇳",
    },
    {
        "name": "Colombia",
        "alpha2": "CO",
        "alpha3": "COL",
        "numeric": "170",
        "calling_code": "+57",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇨🇴",
    },
    {
        "name": "Croatia",
        "alpha2": "HR",
        "alpha3": "HRV",
        "numeric": "191",
        "calling_code": "+385",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇭🇷",
    },
    {
        "name": "Cuba",
        "alpha2": "CU",
        "alpha3": "CUB",
        "numeric": "192",
        "calling_code": "+53",
        "region": "Americas",
        "subregion": "Caribbean",
        "flag_emoji": "🇨🇺",
    },
    {
        "name": "Cyprus",
        "alpha2": "CY",
        "alpha3": "CYP",
        "numeric": "196",
        "calling_code": "+357",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇨🇾",
    },
    {
        "name": "Czech Republic",
        "alpha2": "CZ",
        "alpha3": "CZE",
        "numeric": "203",
        "calling_code": "+420",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇨🇿",
    },
    {
        "name": "Denmark",
        "alpha2": "DK",
        "alpha3": "DNK",
        "numeric": "208",
        "calling_code": "+45",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇩🇰",
    },
    {
        "name": "Ecuador",
        "alpha2": "EC",
        "alpha3": "ECU",
        "numeric": "218",
        "calling_code": "+593",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇪🇨",
    },
    {
        "name": "Egypt",
        "alpha2": "EG",
        "alpha3": "EGY",
        "numeric": "818",
        "calling_code": "+20",
        "region": "Africa",
        "subregion": "Northern Africa",
        "flag_emoji": "🇪🇬",
    },
    {
        "name": "Estonia",
        "alpha2": "EE",
        "alpha3": "EST",
        "numeric": "233",
        "calling_code": "+372",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇪🇪",
    },
    {
        "name": "Ethiopia",
        "alpha2": "ET",
        "alpha3": "ETH",
        "numeric": "231",
        "calling_code": "+251",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "flag_emoji": "🇪🇹",
    },
    {
        "name": "Finland",
        "alpha2": "FI",
        "alpha3": "FIN",
        "numeric": "246",
        "calling_code": "+358",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇫🇮",
    },
    {
        "name": "France",
        "alpha2": "FR",
        "alpha3": "FRA",
        "numeric": "250",
        "calling_code": "+33",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇫🇷",
    },
    {
        "name": "Georgia",
        "alpha2": "GE",
        "alpha3": "GEO",
        "numeric": "268",
        "calling_code": "+995",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇬🇪",
    },
    {
        "name": "Germany",
        "alpha2": "DE",
        "alpha3": "DEU",
        "numeric": "276",
        "calling_code": "+49",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇩🇪",
    },
    {
        "name": "Ghana",
        "alpha2": "GH",
        "alpha3": "GHA",
        "numeric": "288",
        "calling_code": "+233",
        "region": "Africa",
        "subregion": "Western Africa",
        "flag_emoji": "🇬🇭",
    },
    {
        "name": "Greece",
        "alpha2": "GR",
        "alpha3": "GRC",
        "numeric": "300",
        "calling_code": "+30",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇬🇷",
    },
    {
        "name": "Guatemala",
        "alpha2": "GT",
        "alpha3": "GTM",
        "numeric": "320",
        "calling_code": "+502",
        "region": "Americas",
        "subregion": "Central America",
        "flag_emoji": "🇬🇹",
    },
    {
        "name": "Honduras",
        "alpha2": "HN",
        "alpha3": "HND",
        "numeric": "340",
        "calling_code": "+504",
        "region": "Americas",
        "subregion": "Central America",
        "flag_emoji": "🇭🇳",
    },
    {
        "name": "Hungary",
        "alpha2": "HU",
        "alpha3": "HUN",
        "numeric": "348",
        "calling_code": "+36",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇭🇺",
    },
    {
        "name": "India",
        "alpha2": "IN",
        "alpha3": "IND",
        "numeric": "356",
        "calling_code": "+91",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇮🇳",
    },
    {
        "name": "Indonesia",
        "alpha2": "ID",
        "alpha3": "IDN",
        "numeric": "360",
        "calling_code": "+62",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇮🇩",
    },
    {
        "name": "Iran",
        "alpha2": "IR",
        "alpha3": "IRN",
        "numeric": "364",
        "calling_code": "+98",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇮🇷",
    },
    {
        "name": "Iraq",
        "alpha2": "IQ",
        "alpha3": "IRQ",
        "numeric": "368",
        "calling_code": "+964",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇮🇶",
    },
    {
        "name": "Ireland",
        "alpha2": "IE",
        "alpha3": "IRL",
        "numeric": "372",
        "calling_code": "+353",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇮🇪",
    },
    {
        "name": "Israel",
        "alpha2": "IL",
        "alpha3": "ISR",
        "numeric": "376",
        "calling_code": "+972",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇮🇱",
    },
    {
        "name": "Italy",
        "alpha2": "IT",
        "alpha3": "ITA",
        "numeric": "380",
        "calling_code": "+39",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇮🇹",
    },
    {
        "name": "Japan",
        "alpha2": "JP",
        "alpha3": "JPN",
        "numeric": "392",
        "calling_code": "+81",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "flag_emoji": "🇯🇵",
    },
    {
        "name": "Jordan",
        "alpha2": "JO",
        "alpha3": "JOR",
        "numeric": "400",
        "calling_code": "+962",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇯🇴",
    },
    {
        "name": "Kazakhstan",
        "alpha2": "KZ",
        "alpha3": "KAZ",
        "numeric": "398",
        "calling_code": "+7",
        "region": "Asia",
        "subregion": "Central Asia",
        "flag_emoji": "🇰🇿",
    },
    {
        "name": "Kenya",
        "alpha2": "KE",
        "alpha3": "KEN",
        "numeric": "404",
        "calling_code": "+254",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "flag_emoji": "🇰🇪",
    },
    {
        "name": "Kuwait",
        "alpha2": "KW",
        "alpha3": "KWT",
        "numeric": "414",
        "calling_code": "+965",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇰🇼",
    },
    {
        "name": "Latvia",
        "alpha2": "LV",
        "alpha3": "LVA",
        "numeric": "428",
        "calling_code": "+371",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇱🇻",
    },
    {
        "name": "Lebanon",
        "alpha2": "LB",
        "alpha3": "LBN",
        "numeric": "422",
        "calling_code": "+961",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇱🇧",
    },
    {
        "name": "Lithuania",
        "alpha2": "LT",
        "alpha3": "LTU",
        "numeric": "440",
        "calling_code": "+370",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇱🇹",
    },
    {
        "name": "Luxembourg",
        "alpha2": "LU",
        "alpha3": "LUX",
        "numeric": "442",
        "calling_code": "+352",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇱🇺",
    },
    {
        "name": "Malaysia",
        "alpha2": "MY",
        "alpha3": "MYS",
        "numeric": "458",
        "calling_code": "+60",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇲🇾",
    },
    {
        "name": "Mexico",
        "alpha2": "MX",
        "alpha3": "MEX",
        "numeric": "484",
        "calling_code": "+52",
        "region": "Americas",
        "subregion": "Central America",
        "flag_emoji": "🇲🇽",
    },
    {
        "name": "Moldova",
        "alpha2": "MD",
        "alpha3": "MDA",
        "numeric": "498",
        "calling_code": "+373",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇲🇩",
    },
    {
        "name": "Morocco",
        "alpha2": "MA",
        "alpha3": "MAR",
        "numeric": "504",
        "calling_code": "+212",
        "region": "Africa",
        "subregion": "Northern Africa",
        "flag_emoji": "🇲🇦",
    },
    {
        "name": "Myanmar",
        "alpha2": "MM",
        "alpha3": "MMR",
        "numeric": "104",
        "calling_code": "+95",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇲🇲",
    },
    {
        "name": "Nepal",
        "alpha2": "NP",
        "alpha3": "NPL",
        "numeric": "524",
        "calling_code": "+977",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇳🇵",
    },
    {
        "name": "Netherlands",
        "alpha2": "NL",
        "alpha3": "NLD",
        "numeric": "528",
        "calling_code": "+31",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇳🇱",
    },
    {
        "name": "New Zealand",
        "alpha2": "NZ",
        "alpha3": "NZL",
        "numeric": "554",
        "calling_code": "+64",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "flag_emoji": "🇳🇿",
    },
    {
        "name": "Nigeria",
        "alpha2": "NG",
        "alpha3": "NGA",
        "numeric": "566",
        "calling_code": "+234",
        "region": "Africa",
        "subregion": "Western Africa",
        "flag_emoji": "🇳🇬",
    },
    {
        "name": "Norway",
        "alpha2": "NO",
        "alpha3": "NOR",
        "numeric": "578",
        "calling_code": "+47",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇳🇴",
    },
    {
        "name": "Pakistan",
        "alpha2": "PK",
        "alpha3": "PAK",
        "numeric": "586",
        "calling_code": "+92",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇵🇰",
    },
    {
        "name": "Panama",
        "alpha2": "PA",
        "alpha3": "PAN",
        "numeric": "591",
        "calling_code": "+507",
        "region": "Americas",
        "subregion": "Central America",
        "flag_emoji": "🇵🇦",
    },
    {
        "name": "Paraguay",
        "alpha2": "PY",
        "alpha3": "PRY",
        "numeric": "600",
        "calling_code": "+595",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇵🇾",
    },
    {
        "name": "Peru",
        "alpha2": "PE",
        "alpha3": "PER",
        "numeric": "604",
        "calling_code": "+51",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇵🇪",
    },
    {
        "name": "Philippines",
        "alpha2": "PH",
        "alpha3": "PHL",
        "numeric": "608",
        "calling_code": "+63",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇵🇭",
    },
    {
        "name": "Poland",
        "alpha2": "PL",
        "alpha3": "POL",
        "numeric": "616",
        "calling_code": "+48",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇵🇱",
    },
    {
        "name": "Portugal",
        "alpha2": "PT",
        "alpha3": "PRT",
        "numeric": "620",
        "calling_code": "+351",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇵🇹",
    },
    {
        "name": "Qatar",
        "alpha2": "QA",
        "alpha3": "QAT",
        "numeric": "634",
        "calling_code": "+974",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇶🇦",
    },
    {
        "name": "Romania",
        "alpha2": "RO",
        "alpha3": "ROU",
        "numeric": "642",
        "calling_code": "+40",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇷🇴",
    },
    {
        "name": "Russia",
        "alpha2": "RU",
        "alpha3": "RUS",
        "numeric": "643",
        "calling_code": "+7",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇷🇺",
    },
    {
        "name": "Saudi Arabia",
        "alpha2": "SA",
        "alpha3": "SAU",
        "numeric": "682",
        "calling_code": "+966",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇸🇦",
    },
    {
        "name": "Serbia",
        "alpha2": "RS",
        "alpha3": "SRB",
        "numeric": "688",
        "calling_code": "+381",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇷🇸",
    },
    {
        "name": "Singapore",
        "alpha2": "SG",
        "alpha3": "SGP",
        "numeric": "702",
        "calling_code": "+65",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇸🇬",
    },
    {
        "name": "Slovakia",
        "alpha2": "SK",
        "alpha3": "SVK",
        "numeric": "703",
        "calling_code": "+421",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇸🇰",
    },
    {
        "name": "Slovenia",
        "alpha2": "SI",
        "alpha3": "SVN",
        "numeric": "705",
        "calling_code": "+386",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇸🇮",
    },
    {
        "name": "South Africa",
        "alpha2": "ZA",
        "alpha3": "ZAF",
        "numeric": "710",
        "calling_code": "+27",
        "region": "Africa",
        "subregion": "Southern Africa",
        "flag_emoji": "🇿🇦",
    },
    {
        "name": "South Korea",
        "alpha2": "KR",
        "alpha3": "KOR",
        "numeric": "410",
        "calling_code": "+82",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "flag_emoji": "🇰🇷",
    },
    {
        "name": "Spain",
        "alpha2": "ES",
        "alpha3": "ESP",
        "numeric": "724",
        "calling_code": "+34",
        "region": "Europe",
        "subregion": "Southern Europe",
        "flag_emoji": "🇪🇸",
    },
    {
        "name": "Sri Lanka",
        "alpha2": "LK",
        "alpha3": "LKA",
        "numeric": "144",
        "calling_code": "+94",
        "region": "Asia",
        "subregion": "Southern Asia",
        "flag_emoji": "🇱🇰",
    },
    {
        "name": "Sweden",
        "alpha2": "SE",
        "alpha3": "SWE",
        "numeric": "752",
        "calling_code": "+46",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇸🇪",
    },
    {
        "name": "Switzerland",
        "alpha2": "CH",
        "alpha3": "CHE",
        "numeric": "756",
        "calling_code": "+41",
        "region": "Europe",
        "subregion": "Western Europe",
        "flag_emoji": "🇨🇭",
    },
    {
        "name": "Syria",
        "alpha2": "SY",
        "alpha3": "SYR",
        "numeric": "760",
        "calling_code": "+963",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇸🇾",
    },
    {
        "name": "Taiwan",
        "alpha2": "TW",
        "alpha3": "TWN",
        "numeric": "158",
        "calling_code": "+886",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "flag_emoji": "🇹🇼",
    },
    {
        "name": "Thailand",
        "alpha2": "TH",
        "alpha3": "THA",
        "numeric": "764",
        "calling_code": "+66",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇹🇭",
    },
    {
        "name": "Tunisia",
        "alpha2": "TN",
        "alpha3": "TUN",
        "numeric": "788",
        "calling_code": "+216",
        "region": "Africa",
        "subregion": "Northern Africa",
        "flag_emoji": "🇹🇳",
    },
    {
        "name": "Turkey",
        "alpha2": "TR",
        "alpha3": "TUR",
        "numeric": "792",
        "calling_code": "+90",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇹🇷",
    },
    {
        "name": "Ukraine",
        "alpha2": "UA",
        "alpha3": "UKR",
        "numeric": "804",
        "calling_code": "+380",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "flag_emoji": "🇺🇦",
    },
    {
        "name": "United Arab Emirates",
        "alpha2": "AE",
        "alpha3": "ARE",
        "numeric": "784",
        "calling_code": "+971",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇦🇪",
    },
    {
        "name": "United Kingdom",
        "alpha2": "GB",
        "alpha3": "GBR",
        "numeric": "826",
        "calling_code": "+44",
        "region": "Europe",
        "subregion": "Northern Europe",
        "flag_emoji": "🇬🇧",
    },
    {
        "name": "United States",
        "alpha2": "US",
        "alpha3": "USA",
        "numeric": "840",
        "calling_code": "+1",
        "region": "Americas",
        "subregion": "Northern America",
        "flag_emoji": "🇺🇸",
    },
    {
        "name": "Uruguay",
        "alpha2": "UY",
        "alpha3": "URY",
        "numeric": "858",
        "calling_code": "+598",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇺🇾",
    },
    {
        "name": "Uzbekistan",
        "alpha2": "UZ",
        "alpha3": "UZB",
        "numeric": "860",
        "calling_code": "+998",
        "region": "Asia",
        "subregion": "Central Asia",
        "flag_emoji": "🇺🇿",
    },
    {
        "name": "Venezuela",
        "alpha2": "VE",
        "alpha3": "VEN",
        "numeric": "862",
        "calling_code": "+58",
        "region": "Americas",
        "subregion": "South America",
        "flag_emoji": "🇻🇪",
    },
    {
        "name": "Vietnam",
        "alpha2": "VN",
        "alpha3": "VNM",
        "numeric": "704",
        "calling_code": "+84",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "flag_emoji": "🇻🇳",
    },
    {
        "name": "Yemen",
        "alpha2": "YE",
        "alpha3": "YEM",
        "numeric": "887",
        "calling_code": "+967",
        "region": "Asia",
        "subregion": "Western Asia",
        "flag_emoji": "🇾🇪",
    },
]

_LANGUAGES = [
    {"name": "Arabic", "native_name": "العربية", "iso_639_1": "ar", "iso_639_2": "ara"},
    {"name": "Bengali", "native_name": "বাংলা", "iso_639_1": "bn", "iso_639_2": "ben"},
    {"name": "Chinese", "native_name": "中文", "iso_639_1": "zh", "iso_639_2": "zho"},
    {"name": "Czech", "native_name": "Čeština", "iso_639_1": "cs", "iso_639_2": "ces"},
    {"name": "Danish", "native_name": "Dansk", "iso_639_1": "da", "iso_639_2": "dan"},
    {
        "name": "Dutch",
        "native_name": "Nederlands",
        "iso_639_1": "nl",
        "iso_639_2": "nld",
    },
    {
        "name": "English",
        "native_name": "English",
        "iso_639_1": "en",
        "iso_639_2": "eng",
    },
    {"name": "Finnish", "native_name": "Suomi", "iso_639_1": "fi", "iso_639_2": "fin"},
    {
        "name": "French",
        "native_name": "Français",
        "iso_639_1": "fr",
        "iso_639_2": "fra",
    },
    {"name": "German", "native_name": "Deutsch", "iso_639_1": "de", "iso_639_2": "deu"},
    {"name": "Greek", "native_name": "Ελληνικά", "iso_639_1": "el", "iso_639_2": "ell"},
    {
        "name": "Gujarati",
        "native_name": "ગુજરાતી",
        "iso_639_1": "gu",
        "iso_639_2": "guj",
    },
    {"name": "Hebrew", "native_name": "עברית", "iso_639_1": "he", "iso_639_2": "heb"},
    {"name": "Hindi", "native_name": "हिन्दी", "iso_639_1": "hi", "iso_639_2": "hin"},
    {
        "name": "Hungarian",
        "native_name": "Magyar",
        "iso_639_1": "hu",
        "iso_639_2": "hun",
    },
    {
        "name": "Indonesian",
        "native_name": "Bahasa Indonesia",
        "iso_639_1": "id",
        "iso_639_2": "ind",
    },
    {
        "name": "Italian",
        "native_name": "Italiano",
        "iso_639_1": "it",
        "iso_639_2": "ita",
    },
    {
        "name": "Japanese",
        "native_name": "日本語",
        "iso_639_1": "ja",
        "iso_639_2": "jpn",
    },
    {"name": "Kannada", "native_name": "ಕನ್ನಡ", "iso_639_1": "kn", "iso_639_2": "kan"},
    {"name": "Korean", "native_name": "한국어", "iso_639_1": "ko", "iso_639_2": "kor"},
    {
        "name": "Malay",
        "native_name": "Bahasa Melayu",
        "iso_639_1": "ms",
        "iso_639_2": "msa",
    },
    {"name": "Marathi", "native_name": "मराठी", "iso_639_1": "mr", "iso_639_2": "mar"},
    {
        "name": "Norwegian",
        "native_name": "Norsk",
        "iso_639_1": "no",
        "iso_639_2": "nor",
    },
    {"name": "Persian", "native_name": "فارسی", "iso_639_1": "fa", "iso_639_2": "fas"},
    {"name": "Polish", "native_name": "Polski", "iso_639_1": "pl", "iso_639_2": "pol"},
    {
        "name": "Portuguese",
        "native_name": "Português",
        "iso_639_1": "pt",
        "iso_639_2": "por",
    },
    {"name": "Punjabi", "native_name": "ਪੰਜਾਬੀ", "iso_639_1": "pa", "iso_639_2": "pan"},
    {
        "name": "Romanian",
        "native_name": "Română",
        "iso_639_1": "ro",
        "iso_639_2": "ron",
    },
    {
        "name": "Russian",
        "native_name": "Русский",
        "iso_639_1": "ru",
        "iso_639_2": "rus",
    },
    {"name": "Serbian", "native_name": "Српски", "iso_639_1": "sr", "iso_639_2": "srp"},
    {"name": "Sinhala", "native_name": "සිංහල", "iso_639_1": "si", "iso_639_2": "sin"},
    {
        "name": "Slovak",
        "native_name": "Slovenčina",
        "iso_639_1": "sk",
        "iso_639_2": "slk",
    },
    {
        "name": "Spanish",
        "native_name": "Español",
        "iso_639_1": "es",
        "iso_639_2": "spa",
    },
    {
        "name": "Swahili",
        "native_name": "Kiswahili",
        "iso_639_1": "sw",
        "iso_639_2": "swa",
    },
    {
        "name": "Swedish",
        "native_name": "Svenska",
        "iso_639_1": "sv",
        "iso_639_2": "swe",
    },
    {"name": "Tamil", "native_name": "தமிழ்", "iso_639_1": "ta", "iso_639_2": "tam"},
    {"name": "Telugu", "native_name": "తెలుగు", "iso_639_1": "te", "iso_639_2": "tel"},
    {"name": "Thai", "native_name": "ภาษาไทย", "iso_639_1": "th", "iso_639_2": "tha"},
    {"name": "Turkish", "native_name": "Türkçe", "iso_639_1": "tr", "iso_639_2": "tur"},
    {
        "name": "Ukrainian",
        "native_name": "Українська",
        "iso_639_1": "uk",
        "iso_639_2": "ukr",
    },
    {"name": "Urdu", "native_name": "اردو", "iso_639_1": "ur", "iso_639_2": "urd"},
    {
        "name": "Vietnamese",
        "native_name": "Tiếng Việt",
        "iso_639_1": "vi",
        "iso_639_2": "vie",
    },
]

_TIMEZONES = [
    {
        "name": "Africa/Cairo",
        "utc_offset": "+02:00",
        "utc_offset_dst": None,
        "country_alpha2": "EG",
    },
    {
        "name": "Africa/Johannesburg",
        "utc_offset": "+02:00",
        "utc_offset_dst": None,
        "country_alpha2": "ZA",
    },
    {
        "name": "Africa/Lagos",
        "utc_offset": "+01:00",
        "utc_offset_dst": None,
        "country_alpha2": "NG",
    },
    {
        "name": "Africa/Nairobi",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "KE",
    },
    {
        "name": "America/Anchorage",
        "utc_offset": "-09:00",
        "utc_offset_dst": "-08:00",
        "country_alpha2": "US",
    },
    {
        "name": "America/Argentina/Buenos_Aires",
        "utc_offset": "-03:00",
        "utc_offset_dst": None,
        "country_alpha2": "AR",
    },
    {
        "name": "America/Bogota",
        "utc_offset": "-05:00",
        "utc_offset_dst": None,
        "country_alpha2": "CO",
    },
    {
        "name": "America/Caracas",
        "utc_offset": "-04:00",
        "utc_offset_dst": None,
        "country_alpha2": "VE",
    },
    {
        "name": "America/Chicago",
        "utc_offset": "-06:00",
        "utc_offset_dst": "-05:00",
        "country_alpha2": "US",
    },
    {
        "name": "America/Denver",
        "utc_offset": "-07:00",
        "utc_offset_dst": "-06:00",
        "country_alpha2": "US",
    },
    {
        "name": "America/Halifax",
        "utc_offset": "-04:00",
        "utc_offset_dst": "-03:00",
        "country_alpha2": "CA",
    },
    {
        "name": "America/Havana",
        "utc_offset": "-05:00",
        "utc_offset_dst": "-04:00",
        "country_alpha2": "CU",
    },
    {
        "name": "America/Lima",
        "utc_offset": "-05:00",
        "utc_offset_dst": None,
        "country_alpha2": "PE",
    },
    {
        "name": "America/Los_Angeles",
        "utc_offset": "-08:00",
        "utc_offset_dst": "-07:00",
        "country_alpha2": "US",
    },
    {
        "name": "America/Mexico_City",
        "utc_offset": "-06:00",
        "utc_offset_dst": "-05:00",
        "country_alpha2": "MX",
    },
    {
        "name": "America/New_York",
        "utc_offset": "-05:00",
        "utc_offset_dst": "-04:00",
        "country_alpha2": "US",
    },
    {
        "name": "America/Panama",
        "utc_offset": "-05:00",
        "utc_offset_dst": None,
        "country_alpha2": "PA",
    },
    {
        "name": "America/Phoenix",
        "utc_offset": "-07:00",
        "utc_offset_dst": None,
        "country_alpha2": "US",
    },
    {
        "name": "America/Santiago",
        "utc_offset": "-04:00",
        "utc_offset_dst": "-03:00",
        "country_alpha2": "CL",
    },
    {
        "name": "America/Sao_Paulo",
        "utc_offset": "-03:00",
        "utc_offset_dst": "-02:00",
        "country_alpha2": "BR",
    },
    {
        "name": "America/Toronto",
        "utc_offset": "-05:00",
        "utc_offset_dst": "-04:00",
        "country_alpha2": "CA",
    },
    {
        "name": "America/Vancouver",
        "utc_offset": "-08:00",
        "utc_offset_dst": "-07:00",
        "country_alpha2": "CA",
    },
    {
        "name": "Asia/Almaty",
        "utc_offset": "+06:00",
        "utc_offset_dst": None,
        "country_alpha2": "KZ",
    },
    {
        "name": "Asia/Baghdad",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "IQ",
    },
    {
        "name": "Asia/Bangkok",
        "utc_offset": "+07:00",
        "utc_offset_dst": None,
        "country_alpha2": "TH",
    },
    {
        "name": "Asia/Beirut",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "LB",
    },
    {
        "name": "Asia/Colombo",
        "utc_offset": "+05:30",
        "utc_offset_dst": None,
        "country_alpha2": "LK",
    },
    {
        "name": "Asia/Dhaka",
        "utc_offset": "+06:00",
        "utc_offset_dst": None,
        "country_alpha2": "BD",
    },
    {
        "name": "Asia/Dubai",
        "utc_offset": "+04:00",
        "utc_offset_dst": None,
        "country_alpha2": "AE",
    },
    {
        "name": "Asia/Ho_Chi_Minh",
        "utc_offset": "+07:00",
        "utc_offset_dst": None,
        "country_alpha2": "VN",
    },
    {
        "name": "Asia/Hong_Kong",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "CN",
    },
    {
        "name": "Asia/Jakarta",
        "utc_offset": "+07:00",
        "utc_offset_dst": None,
        "country_alpha2": "ID",
    },
    {
        "name": "Asia/Jerusalem",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "IL",
    },
    {
        "name": "Asia/Kabul",
        "utc_offset": "+04:30",
        "utc_offset_dst": None,
        "country_alpha2": "AF",
    },
    {
        "name": "Asia/Karachi",
        "utc_offset": "+05:00",
        "utc_offset_dst": None,
        "country_alpha2": "PK",
    },
    {
        "name": "Asia/Kathmandu",
        "utc_offset": "+05:45",
        "utc_offset_dst": None,
        "country_alpha2": "NP",
    },
    {
        "name": "Asia/Kolkata",
        "utc_offset": "+05:30",
        "utc_offset_dst": None,
        "country_alpha2": "IN",
    },
    {
        "name": "Asia/Kuala_Lumpur",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "MY",
    },
    {
        "name": "Asia/Kuwait",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "KW",
    },
    {
        "name": "Asia/Manila",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "PH",
    },
    {
        "name": "Asia/Riyadh",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "SA",
    },
    {
        "name": "Asia/Seoul",
        "utc_offset": "+09:00",
        "utc_offset_dst": None,
        "country_alpha2": "KR",
    },
    {
        "name": "Asia/Shanghai",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "CN",
    },
    {
        "name": "Asia/Singapore",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "SG",
    },
    {
        "name": "Asia/Taipei",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "TW",
    },
    {
        "name": "Asia/Tehran",
        "utc_offset": "+03:30",
        "utc_offset_dst": "+04:30",
        "country_alpha2": "IR",
    },
    {
        "name": "Asia/Tokyo",
        "utc_offset": "+09:00",
        "utc_offset_dst": None,
        "country_alpha2": "JP",
    },
    {
        "name": "Asia/Yangon",
        "utc_offset": "+06:30",
        "utc_offset_dst": None,
        "country_alpha2": "MM",
    },
    {
        "name": "Atlantic/Reykjavik",
        "utc_offset": "+00:00",
        "utc_offset_dst": None,
        "country_alpha2": None,
    },
    {
        "name": "Australia/Adelaide",
        "utc_offset": "+09:30",
        "utc_offset_dst": "+10:30",
        "country_alpha2": "AU",
    },
    {
        "name": "Australia/Brisbane",
        "utc_offset": "+10:00",
        "utc_offset_dst": None,
        "country_alpha2": "AU",
    },
    {
        "name": "Australia/Darwin",
        "utc_offset": "+09:30",
        "utc_offset_dst": None,
        "country_alpha2": "AU",
    },
    {
        "name": "Australia/Melbourne",
        "utc_offset": "+10:00",
        "utc_offset_dst": "+11:00",
        "country_alpha2": "AU",
    },
    {
        "name": "Australia/Perth",
        "utc_offset": "+08:00",
        "utc_offset_dst": None,
        "country_alpha2": "AU",
    },
    {
        "name": "Australia/Sydney",
        "utc_offset": "+10:00",
        "utc_offset_dst": "+11:00",
        "country_alpha2": "AU",
    },
    {
        "name": "Europe/Amsterdam",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "NL",
    },
    {
        "name": "Europe/Athens",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "GR",
    },
    {
        "name": "Europe/Belgrade",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "RS",
    },
    {
        "name": "Europe/Berlin",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "DE",
    },
    {
        "name": "Europe/Brussels",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "BE",
    },
    {
        "name": "Europe/Bucharest",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "RO",
    },
    {
        "name": "Europe/Budapest",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "HU",
    },
    {
        "name": "Europe/Copenhagen",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "DK",
    },
    {
        "name": "Europe/Dublin",
        "utc_offset": "+00:00",
        "utc_offset_dst": "+01:00",
        "country_alpha2": "IE",
    },
    {
        "name": "Europe/Helsinki",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "FI",
    },
    {
        "name": "Europe/Istanbul",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "TR",
    },
    {
        "name": "Europe/Kiev",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "UA",
    },
    {
        "name": "Europe/Lisbon",
        "utc_offset": "+00:00",
        "utc_offset_dst": "+01:00",
        "country_alpha2": "PT",
    },
    {
        "name": "Europe/London",
        "utc_offset": "+00:00",
        "utc_offset_dst": "+01:00",
        "country_alpha2": "GB",
    },
    {
        "name": "Europe/Luxembourg",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "LU",
    },
    {
        "name": "Europe/Madrid",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "ES",
    },
    {
        "name": "Europe/Minsk",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "BY",
    },
    {
        "name": "Europe/Moscow",
        "utc_offset": "+03:00",
        "utc_offset_dst": None,
        "country_alpha2": "RU",
    },
    {
        "name": "Europe/Oslo",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "NO",
    },
    {
        "name": "Europe/Paris",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "FR",
    },
    {
        "name": "Europe/Prague",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "CZ",
    },
    {
        "name": "Europe/Rome",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "IT",
    },
    {
        "name": "Europe/Sarajevo",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "BA",
    },
    {
        "name": "Europe/Sofia",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "BG",
    },
    {
        "name": "Europe/Stockholm",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "SE",
    },
    {
        "name": "Europe/Tallinn",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "EE",
    },
    {
        "name": "Europe/Vienna",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "AT",
    },
    {
        "name": "Europe/Vilnius",
        "utc_offset": "+02:00",
        "utc_offset_dst": "+03:00",
        "country_alpha2": "LT",
    },
    {
        "name": "Europe/Warsaw",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "PL",
    },
    {
        "name": "Europe/Zurich",
        "utc_offset": "+01:00",
        "utc_offset_dst": "+02:00",
        "country_alpha2": "CH",
    },
    {
        "name": "Pacific/Auckland",
        "utc_offset": "+12:00",
        "utc_offset_dst": "+13:00",
        "country_alpha2": "NZ",
    },
    {
        "name": "Pacific/Honolulu",
        "utc_offset": "-10:00",
        "utc_offset_dst": None,
        "country_alpha2": "US",
    },
    {
        "name": "UTC",
        "utc_offset": "+00:00",
        "utc_offset_dst": None,
        "country_alpha2": None,
    },
]

# ── Vocabulary Seed Data ───────────────────────────────────────────────────────

_VOCABULARIES = [
    {
        "name": "Name Prefixes",
        "machine_name": "name-prefixes",
        "is_locked": True,
        "is_hierarchical": False,
        "terms": [
            ("Mr", "mr"),
            ("Mrs", "mrs"),
            ("Ms", "ms"),
            ("Miss", "miss"),
            ("Dr", "dr"),
            ("Prof", "prof"),
            ("Rev", "rev"),
            ("Sir", "sir"),
            ("Dame", "dame"),
            ("Lord", "lord"),
            ("Lady", "lady"),
            ("Mx", "mx"),
        ],
    },
    {
        "name": "Genders",
        "machine_name": "genders",
        "is_locked": True,
        "is_hierarchical": False,
        "terms": [
            ("Male", "male"),
            ("Female", "female"),
            ("Non-Binary", "non-binary"),
            ("Prefer Not to Say", "prefer-not-to-say"),
            ("Other", "other"),
        ],
    },
    {
        "name": "Occupations",
        "machine_name": "occupations",
        "is_locked": False,
        "is_hierarchical": True,
        "terms": [
            ("Technology", "technology", None),
            ("Software Engineer", "software-engineer", "technology"),
            ("Product Manager", "product-manager", "technology"),
            ("Data Scientist", "data-scientist", "technology"),
            ("DevOps Engineer", "devops-engineer", "technology"),
            ("UX Designer", "ux-designer", "technology"),
            ("Healthcare", "healthcare", None),
            ("Doctor", "doctor", "healthcare"),
            ("Nurse", "nurse", "healthcare"),
            ("Pharmacist", "pharmacist", "healthcare"),
            ("Education", "education", None),
            ("Teacher", "teacher", "education"),
            ("Professor", "professor", "education"),
            ("Finance", "finance", None),
            ("Accountant", "accountant", "finance"),
            ("Financial Analyst", "financial-analyst", "finance"),
            ("Banker", "banker", "finance"),
            ("Legal", "legal", None),
            ("Lawyer", "lawyer", "legal"),
            ("Judge", "judge", "legal"),
            ("Business", "business", None),
            ("Entrepreneur", "entrepreneur", "business"),
            ("CEO", "ceo", "business"),
            ("Consultant", "consultant", "business"),
            ("Marketing Manager", "marketing-manager", "business"),
            ("Sales Representative", "sales-representative", "business"),
            ("Arts & Media", "arts-media", None),
            ("Artist", "artist", "arts-media"),
            ("Journalist", "journalist", "arts-media"),
            ("Photographer", "photographer", "arts-media"),
            ("Writer", "writer", "arts-media"),
            ("Musician", "musician", "arts-media"),
            ("Engineering", "engineering", None),
            ("Civil Engineer", "civil-engineer", "engineering"),
            ("Mechanical Engineer", "mechanical-engineer", "engineering"),
            ("Electrical Engineer", "electrical-engineer", "engineering"),
            ("Other", "other-occupation", None),
            ("Student", "student", "other-occupation"),
            ("Retired", "retired", "other-occupation"),
        ],
    },
    {
        "name": "Relationship Types",
        "machine_name": "relationship-types",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            # (name, slug, reverse_slug)
            ("Friend",            "friend",           "friend"),
            ("Acquaintance",      "acquaintance",     "acquaintance"),
            ("Family — Parent",   "family-parent",    "family-child"),
            ("Family — Sibling",  "family-sibling",   "family-sibling"),
            ("Family — Child",    "family-child",     "family-parent"),
            ("Family — Extended", "family-extended",  "family-extended"),
            ("Romantic Partner",  "romantic-partner", "romantic-partner"),
            ("Colleague",         "colleague",        "colleague"),
            ("Manager",           "manager",          "direct-report"),
            ("Direct Report",     "direct-report",    "manager"),
            ("Mentor",            "mentor",           "mentee"),
            ("Mentee",            "mentee",           "mentor"),
            ("Client",            "client",           "vendor"),
            ("Vendor",            "vendor",           "client"),
            ("Contractor",        "contractor",       "contractor"),
            ("Neighbor",          "neighbor",         "neighbor"),
            ("Classmate",         "classmate",        "classmate"),
            ("Teammate",          "teammate",         "teammate"),
            ("Business Partner",  "business-partner", "business-partner"),
            ("Online Friend",     "online-friend",    "online-friend"),
        ],
    },
    {
        "name": "Asset Categories",
        "machine_name": "asset-categories",
        "is_locked": False,
        "is_hierarchical": True,
        "terms": [
            # Physical assets
            ("Physical", "physical", None),
            ("Electronics", "electronics", "physical"),
            ("Vehicle", "vehicle", "physical"),
            ("Appliance", "appliance", "physical"),
            ("Tool", "tool", "physical"),
            ("Furniture", "furniture", "physical"),
            ("Clothing", "clothing", "physical"),
            ("Book", "book", "physical"),
            ("Musical Instrument", "musical-instrument", "physical"),
            ("Sports Equipment", "sports-equipment", "physical"),
            ("Artwork", "artwork", "physical"),
            ("Jewelry", "jewelry", "physical"),
            ("Property", "property", "physical"),
            ("Other Physical", "other-physical", "physical"),
            # Document assets
            ("Document", "document", None),
            ("Identity Document", "identity-document", "document"),
            ("Permit", "permit", "document"),
            ("Certificate", "certificate-doc", "document"),
            ("Other Document", "other-document-cat", "document"),
            # Financial assets
            ("Financial", "financial", None),
            ("Bank Account", "bank-account", "financial"),
            ("Investment", "investment", "financial"),
            ("Insurance", "insurance-financial", "financial"),
            ("Other Financial", "other-financial", "financial"),
            # Digital assets
            ("Digital", "digital", None),
            ("Software License", "software-license", "digital"),
            ("Domain", "domain", "digital"),
            ("Digital Account", "digital-account", "digital"),
            ("Cloud Service", "cloud-service", "digital"),
            ("Other Digital", "other-digital", "digital"),
        ],
    },
    {
        "name": "Asset Statuses",
        "machine_name": "asset-statuses",
        "is_locked": True,
        "is_hierarchical": False,
        "terms": [
            ("Active", "active"),
            ("Sold", "sold"),
            ("Retired", "retired"),
            ("Lost", "lost"),
            ("Lent", "lent"),
            ("Donated", "donated"),
            ("Broken", "broken"),
            ("In Storage", "in-storage"),
            ("Gifted", "gifted"),
            ("Expired", "expired"),
            ("Pending", "pending"),
        ],
    },
    {
        "name": "Person Tags",
        "machine_name": "person-tags",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("VIP", "vip"),
            ("Family", "family"),
            ("Friend", "friend"),
            ("Work", "work"),
            ("School", "school"),
            ("Client", "client"),
            ("Alumni", "alumni"),
            ("Neighbor", "neighbor"),
            ("Online Community", "online-community"),
            ("Conference", "conference"),
            ("Mentor", "mentor"),
            ("Mentee", "mentee"),
            ("Collaborator", "collaborator"),
            ("Reference", "reference"),
            ("Do Not Contact", "do-not-contact"),
        ],
    },
    {
        "name": "Asset Tags",
        "machine_name": "asset-tags",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Essential", "essential"),
            ("Backup", "backup"),
            ("Loaned Out", "loaned-out"),
            ("Needs Repair", "needs-repair"),
            ("Warranty Active", "warranty-active"),
            ("Leased", "leased"),
            ("Shared", "shared"),
        ],
    },
    {
        "name": "Interaction Types",
        "machine_name": "interaction-types",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Meeting", "meeting"),
            ("Video Call", "video-call"),
            ("Phone Call", "phone-call"),
            ("Email", "email"),
            ("Text / SMS", "text-sms"),
            ("Coffee / Lunch", "coffee-lunch"),
            ("Event / Conference", "event-conference"),
            ("Birthday", "birthday"),
            ("Introduction", "introduction"),
            ("Collaboration", "collaboration"),
            ("Review / Feedback", "review-feedback"),
            ("Health Check-in", "health-check-in"),
            ("Social Media", "social-media"),
            ("Other", "other"),
        ],
    },
    {
        "name": "Record Types",
        "machine_name": "record-types",
        "is_locked": False,
        "is_hierarchical": True,
        "terms": [
            ("Warranty", "warranty", None),
            ("Manufacturer Warranty", "warranty-manufacturer", "warranty"),
            ("Extended Warranty", "warranty-extended", "warranty"),
            ("Accidental Damage Protection", "warranty-accidental", "warranty"),
            ("Insurance", "insurance", None),
            ("Health Insurance", "insurance-health", "insurance"),
            ("Vehicle Insurance", "insurance-vehicle", "insurance"),
            ("Life Insurance", "insurance-life", "insurance"),
            ("Home Insurance", "insurance-home", "insurance"),
            ("Travel Insurance", "insurance-travel", "insurance"),
            ("License", "license", None),
            ("Driving License", "license-driving", "license"),
            ("Passport", "license-passport", "license"),
            ("Professional License", "license-professional", "license"),
            ("Vehicle Permit", "license-vehicle-permit", "license"),
            ("Membership", "membership", None),
            ("Certification", "certification", None),
            ("Registration", "registration", None),
            ("Other", "other-record", None),
        ],
    },
    {
        "name": "Document Types",
        "machine_name": "document-types",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Receipt", "receipt"),
            ("Warranty Card", "warranty-card"),
            ("Insurance Policy", "insurance-policy"),
            ("Invoice", "invoice"),
            ("Manual", "manual"),
            ("Photo", "photo"),
            ("Bill", "bill"),
            ("Certificate", "certificate"),
            ("Contract", "contract"),
            ("Identity Document", "identity-document"),
            ("Other", "other-document"),
        ],
    },
    {
        "name": "Communication Channels",
        "machine_name": "communication-channels",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Email", "email"),
            ("WhatsApp", "whatsapp"),
            ("SMS", "sms"),
            ("Phone Call", "phone-call"),
            ("Telegram", "telegram"),
            ("Slack", "slack"),
            ("Discord", "discord"),
            ("Instagram", "instagram"),
            ("LinkedIn", "linkedin"),
            ("Twitter / X", "twitter"),
            ("Signal", "signal"),
            ("Other", "other-comm"),
        ],
    },
    {
        "name": "Life Event Types",
        "machine_name": "life-event-types",
        "is_locked": False,
        "is_hierarchical": True,
        "terms": [
            # Work & Career
            ("Work & Career", "work-career", None),
            ("Started New Job", "started-new-job", "work-career"),
            ("Got Promoted", "got-promoted", "work-career"),
            ("Changed Career", "changed-career", "work-career"),
            ("Got Fired", "got-fired", "work-career"),
            ("Retired", "retired-event", "work-career"),
            ("Started a Business", "started-business", "work-career"),
            # Education
            ("Education", "education-events", None),
            ("Started School", "started-school", "education-events"),
            ("Graduated", "graduated", "education-events"),
            ("Passed Exam", "passed-exam", "education-events"),
            ("Earned Certification", "earned-certification", "education-events"),
            # Relationships
            ("Relationships", "relationship-events", None),
            ("Got Engaged", "got-engaged", "relationship-events"),
            ("Got Married", "got-married", "relationship-events"),
            ("Got Divorced", "got-divorced", "relationship-events"),
            ("Had a Child", "had-a-child", "relationship-events"),
            ("Started Dating", "started-dating", "relationship-events"),
            ("Broke Up", "broke-up", "relationship-events"),
            # Housing
            ("Housing", "housing-events", None),
            ("Moved", "moved", "housing-events"),
            ("Bought a Home", "bought-home", "housing-events"),
            ("Sold a Home", "sold-home", "housing-events"),
            ("Renovated Home", "renovated-home", "housing-events"),
            # Health
            ("Health", "health-events", None),
            ("Surgery", "surgery", "health-events"),
            ("Diagnosis", "diagnosis", "health-events"),
            ("Recovery", "recovery", "health-events"),
            ("Started Treatment", "started-treatment", "health-events"),
            # Travel
            ("Travel", "travel-events", None),
            ("Took a Trip", "took-a-trip", "travel-events"),
            ("Relocated Abroad", "relocated-abroad", "travel-events"),
            ("Immigration", "immigration", "travel-events"),
            # Loss & Grief
            ("Loss & Grief", "loss-grief", None),
            ("Death of Loved One", "death-of-loved-one", "loss-grief"),
            ("Pet Passed Away", "pet-passed-away", "loss-grief"),
            # Achievements
            ("Achievements", "achievements", None),
            ("Won an Award", "won-award", "achievements"),
            ("Published Work", "published-work", "achievements"),
            ("Completed a Goal", "completed-goal", "achievements"),
            # Other
            ("Other", "other-life-event", None),
        ],
    },
    {
        "name": "Life Event Emotions",
        "machine_name": "life-event-emotions",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Happy", "happy"),
            ("Sad", "sad"),
            ("Excited", "excited"),
            ("Anxious", "anxious"),
            ("Proud", "proud"),
            ("Relieved", "relieved"),
            ("Grateful", "grateful"),
            ("Angry", "angry"),
            ("Bittersweet", "bittersweet"),
            ("Overwhelmed", "overwhelmed"),
            ("Neutral", "neutral"),
        ],
    },
    {
        "name": "Significant Date Types",
        "machine_name": "significant-date-types",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Birthday", "birthday"),
            ("Wedding Anniversary", "wedding-anniversary"),
            ("Work Anniversary", "work-anniversary"),
            ("Graduation", "graduation-date"),
            ("Memorial / Death Anniversary", "memorial"),
            ("Nameday", "nameday"),
            ("Religious Holiday", "religious-holiday"),
            ("Adoption Day", "adoption-day"),
            ("First Met", "first-met"),
            ("Founding Day", "founding-day"),
            ("Other Anniversary", "other-anniversary"),
        ],
    },
    {
        "name": "Observation Tags",
        "machine_name": "observation-tags",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("General", "general"),
            ("Physical Trait", "physical-trait"),
            ("Interests", "interests"),
            ("Food Preference", "food-preference"),
            ("Dietary Restriction", "dietary-restriction"),
            ("Personality", "personality"),
            ("Communication Style", "communication-style"),
            ("Work Style", "work-style"),
            ("Pet Peeve", "pet-peeve"),
            ("Gift Idea", "gift-idea"),
        ],
    },
    {
        "name": "Asset Conditions",
        "machine_name": "asset-conditions",
        "is_locked": True,
        "is_hierarchical": False,
        "terms": [
            ("New", "new"),
            ("Like New", "like-new"),
            ("Good", "good"),
            ("Fair", "fair"),
            ("Poor", "poor"),
            ("Damaged", "damaged"),
            ("Broken", "broken-condition"),
            ("Refurbished", "refurbished"),
        ],
    },
    {
        "name": "Document Asset Types",
        "machine_name": "document-asset-types",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Passport", "passport"),
            ("National ID", "national-id"),
            ("Driver's License", "drivers-license"),
            ("Visa", "visa"),
            ("Work Permit", "work-permit"),
            ("Birth Certificate", "birth-certificate"),
            ("Marriage Certificate", "marriage-certificate"),
            ("Death Certificate", "death-certificate"),
            ("Diploma", "diploma"),
            ("Tax ID", "tax-id"),
            ("Social Security Card", "social-security-card"),
            ("Voter ID", "voter-id"),
            ("Health Card", "health-card"),
            ("Other Document Type", "other-doc-type"),
        ],
    },
    {
        "name": "Financial Account Types",
        "machine_name": "financial-account-types",
        "is_locked": False,
        "is_hierarchical": False,
        "terms": [
            ("Savings Account", "savings"),
            ("Checking Account", "checking"),
            ("Fixed Deposit", "fixed-deposit"),
            ("Recurring Deposit", "recurring-deposit"),
            ("Mutual Fund", "mutual-fund"),
            ("Stock Portfolio", "stock-portfolio"),
            ("Retirement Fund", "retirement-fund"),
            ("Cryptocurrency Wallet", "crypto-wallet"),
            ("Credit Card", "credit-card"),
            ("Loan Account", "loan-account"),
            ("Other Account", "other-account"),
        ],
    },
]


# ── Seed functions ─────────────────────────────────────────────────────────────


async def _seed_countries(db: AsyncSession) -> int:
    count = 0
    for data in _COUNTRIES:
        existing = await db.exec(
            select(Country).where(Country.alpha2 == data["alpha2"])
        )
        if existing.first():
            continue
        db.add(Country(**data))
        count += 1
    await db.commit()
    return count


async def _seed_languages(db: AsyncSession) -> int:
    count = 0
    for data in _LANGUAGES:
        existing = await db.exec(
            select(Language).where(Language.iso_639_1 == data["iso_639_1"])
        )
        if existing.first():
            continue
        db.add(Language(**data))
        count += 1
    await db.commit()
    return count


async def _seed_timezones(db: AsyncSession) -> int:
    count = 0
    for data in _TIMEZONES:
        existing = await db.exec(select(Timezone).where(Timezone.name == data["name"]))
        if existing.first():
            continue

        country_id = None
        alpha2 = data.get("country_alpha2")
        if alpha2:
            c = await db.exec(select(Country).where(Country.alpha2 == alpha2))
            country = c.first()
            if country:
                country_id = country.id

        db.add(
            Timezone(
                name=data["name"],
                utc_offset=data["utc_offset"],
                utc_offset_dst=data.get("utc_offset_dst"),
                country_id=country_id,
            )
        )
        count += 1
    await db.commit()
    return count


async def _seed_vocabularies(db: AsyncSession) -> int:
    term_count = 0
    for vdata in _VOCABULARIES:
        existing = await db.exec(
            select(Vocabulary).where(Vocabulary.machine_name == vdata["machine_name"])
        )
        vocab = existing.first()
        if not vocab:
            vocab = Vocabulary(
                name=vdata["name"],
                machine_name=vdata["machine_name"],
                is_locked=vdata["is_locked"],
                is_hierarchical=vdata["is_hierarchical"],
            )
            db.add(vocab)
            await db.flush()

        # Build slug→id map for parent resolution
        slug_to_id: dict[str, uuid.UUID] = {}

        for term_data in vdata["terms"]:
            if len(term_data) == 3:
                if vdata["is_hierarchical"]:
                    name, slug, parent_slug = term_data
                    reverse_slug = None
                else:
                    name, slug, reverse_slug = term_data
                    parent_slug = None
            else:
                name, slug = term_data
                parent_slug = None
                reverse_slug = None

            existing_term = await db.exec(
                select(Term).where(Term.vocabulary_id == vocab.id, Term.slug == slug)
            )
            existing_t = existing_term.first()
            if existing_t:
                # Update reverse_slug if not yet set
                if reverse_slug and not existing_t.reverse_slug:
                    existing_t.reverse_slug = reverse_slug
                    db.add(existing_t)
                slug_to_id[slug] = existing_t.id
                continue

            parent_id = slug_to_id.get(parent_slug) if parent_slug else None
            term = Term(
                vocabulary_id=vocab.id,
                name=name,
                slug=slug,
                parent_id=parent_id,
                reverse_slug=reverse_slug,
            )
            db.add(term)
            await db.flush()
            slug_to_id[slug] = term.id
            term_count += 1

    await db.commit()
    return term_count


async def seed_all(db: AsyncSession) -> None:
    country_count = await _seed_countries(db)
    lang_count = await _seed_languages(db)
    tz_count = await _seed_timezones(db)
    term_count = await _seed_vocabularies(db)

    print(
        f"Seeded: {country_count} countries, {lang_count} languages, "
        f"{tz_count} timezones, {term_count} vocabulary terms"
    )


if __name__ == "__main__":
    import sys

    sys.path.insert(0, ".")

    from sqlalchemy.ext.asyncio import create_async_engine
    from sqlalchemy.orm import sessionmaker
    from sqlmodel.ext.asyncio.session import AsyncSession as SQLModelAsyncSession

    from app.core.config import get_settings

    async def main() -> None:
        settings = get_settings()
        engine = create_async_engine(settings.database_url, echo=False)
        async_session = sessionmaker(
            engine, class_=SQLModelAsyncSession, expire_on_commit=False
        )
        async with async_session() as session:
            await seed_all(session)
        await engine.dispose()

    asyncio.run(main())
