"""fresh schema with entity redesign

Revision ID: 9545d834363c
Revises: 
Create Date: 2026-03-30 12:36:13.631518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9545d834363c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alpha2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alpha3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numeric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calling_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subregion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('flag_emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_alpha2'), 'country', ['alpha2'], unique=True)
    op.create_index(op.f('ix_country_alpha3'), 'country', ['alpha3'], unique=True)
    op.create_table('language',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('native_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso_639_1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iso_639_2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_iso_639_1'), 'language', ['iso_639_1'], unique=True)
    op.create_index(op.f('ix_language_iso_639_2'), 'language', ['iso_639_2'], unique=True)
    op.create_table('raven_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidates_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raven_log_owner_id'), 'raven_log', ['owner_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('vocabulary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('machine_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_hierarchical', sa.Boolean(), nullable=False),
    sa.Column('allows_new_terms', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_machine_name'), 'vocabulary', ['machine_name'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_owner_id'), 'contact', ['owner_id'], unique=False)
    op.create_table('household',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_created_by'), 'household', ['created_by'], unique=False)
    op.create_table('import_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_job_owner_id'), 'import_job', ['owner_id'], unique=False)
    op.create_table('term',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vocabulary_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('reverse_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vocabulary_id', 'slug')
    )
    op.create_index(op.f('ix_term_slug'), 'term', ['slug'], unique=False)
    op.create_index(op.f('ix_term_vocabulary_id'), 'term', ['vocabulary_id'], unique=False)
    op.create_table('timezone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('utc_offset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('utc_offset_dst', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timezone_name'), 'timezone', ['name'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_term_id', sa.Uuid(), nullable=False),
    sa.Column('status_term_id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_price_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('location_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['status_term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_owner_id'), 'asset', ['owner_id'], unique=False)
    op.create_table('contact_relationship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_contact_id', sa.Uuid(), nullable=False),
    sa.Column('to_contact_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['to_contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_relationship_from_contact_id'), 'contact_relationship', ['from_contact_id'], unique=False)
    op.create_index(op.f('ix_contact_relationship_to_contact_id'), 'contact_relationship', ['to_contact_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('doc_type_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_owner_id'), 'document', ['owner_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type_term_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_owner_id'), 'event', ['owner_id'], unique=False)
    op.create_table('household_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_member_household_id'), 'household_member', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_member_user_id'), 'household_member', ['user_id'], unique=True)
    op.create_table('import_row',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raven_log_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['import_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_row_job_id'), 'import_row', ['job_id'], unique=False)
    op.create_table('life_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('event_type_term_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('occurred_year', sa.Integer(), nullable=True),
    sa.Column('emotion_term_id', sa.Uuid(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['event_type_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_event_owner_id'), 'life_event', ['owner_id'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type_term_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry_term_id', sa.Uuid(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('headquarters_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['industry_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['type_term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_household_id'), 'organization', ['household_id'], unique=False)
    op.create_index(op.f('ix_organization_owner_id'), 'organization', ['owner_id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('closeness_level', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_household_id'), 'person', ['household_id'], unique=False)
    op.create_index(op.f('ix_person_owner_id'), 'person', ['owner_id'], unique=False)
    op.create_table('asset_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_event_asset_id'), 'asset_event', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_event_owner_id'), 'asset_event', ['owner_id'], unique=False)
    op.create_table('asset_tag',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'term_id')
    )
    op.create_table('document_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('document_type_term_id', sa.Uuid(), nullable=True),
    sa.Column('document_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['document_type_term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_asset_asset_id'), 'document_asset', ['asset_id'], unique=True)
    op.create_table('event_person',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_person_event_id'), 'event_person', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_person_person_id'), 'event_person', ['person_id'], unique=False)
    op.create_table('financial_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_type_term_id', sa.Uuid(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('nominee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_asset_asset_id'), 'financial_asset', ['asset_id'], unique=True)
    op.create_table('interaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_type_id', sa.Uuid(), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_type_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_owner_id'), 'interaction', ['owner_id'], unique=False)
    op.create_index(op.f('ix_interaction_person_id'), 'interaction', ['person_id'], unique=False)
    op.create_table('life_event_person',
    sa.Column('life_event_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['life_event_id'], ['life_event.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('life_event_id', 'person_id'),
    sa.UniqueConstraint('life_event_id', 'person_id')
    )
    op.create_index(op.f('ix_life_event_person_life_event_id'), 'life_event_person', ['life_event_id'], unique=False)
    op.create_index(op.f('ix_life_event_person_person_id'), 'life_event_person', ['person_id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('loaned_on', sa.Date(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('returned_on', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_owner_id'), 'loan', ['owner_id'], unique=False)
    op.create_index(op.f('ix_loan_person_id'), 'loan', ['person_id'], unique=False)
    op.create_table('person_address',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_address_person_id'), 'person_address', ['person_id'], unique=False)
    op.create_table('person_channel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_channel_person_id'), 'person_channel', ['person_id'], unique=False)
    op.create_table('person_context',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('how_we_met', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_met_on', sa.Date(), nullable=True),
    sa.Column('last_contacted_on', sa.Date(), nullable=True),
    sa.Column('contact_frequency_days', sa.Integer(), nullable=True),
    sa.Column('preferred_contact_term_id', sa.Uuid(), nullable=True),
    sa.Column('relationship_nature', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['preferred_contact_term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_context_person_id'), 'person_context', ['person_id'], unique=True)
    op.create_table('person_goal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('goal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_goal_owner_id'), 'person_goal', ['owner_id'], unique=False)
    op.create_index(op.f('ix_person_goal_person_id'), 'person_goal', ['person_id'], unique=False)
    op.create_table('person_language',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'language_id')
    )
    op.create_table('person_location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('timezone_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_location_person_id'), 'person_location', ['person_id'], unique=True)
    op.create_table('person_observation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_observation_owner_id'), 'person_observation', ['owner_id'], unique=False)
    op.create_index(op.f('ix_person_observation_person_id'), 'person_observation', ['person_id'], unique=False)
    op.create_table('person_organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_organization_org_id'), 'person_organization', ['org_id'], unique=False)
    op.create_index(op.f('ix_person_organization_person_id'), 'person_organization', ['person_id'], unique=False)
    op.create_table('person_professional',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('occupation_term_id', sa.Uuid(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_professional_person_id'), 'person_professional', ['person_id'], unique=True)
    op.create_table('person_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prefix_term_id', sa.Uuid(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender_term_id', sa.Uuid(), nullable=True),
    sa.Column('nationality_country_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['gender_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['nationality_country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['prefix_term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_profile_person_id'), 'person_profile', ['person_id'], unique=True)
    op.create_table('person_relationship',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_person_id', sa.Uuid(), nullable=False),
    sa.Column('to_person_id', sa.Uuid(), nullable=False),
    sa.Column('label_term_id', sa.Uuid(), nullable=False),
    sa.Column('inverse_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['inverse_id'], ['person_relationship.id'], ),
    sa.ForeignKeyConstraint(['label_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['to_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_relationship_from_person_id'), 'person_relationship', ['from_person_id'], unique=False)
    op.create_index(op.f('ix_person_relationship_to_person_id'), 'person_relationship', ['to_person_id'], unique=False)
    op.create_table('person_significant_date',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('date_type_term_id', sa.Uuid(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('recurs_annually', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['date_type_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_significant_date_person_id'), 'person_significant_date', ['person_id'], unique=False)
    op.create_table('person_tag',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'term_id')
    )
    op.create_table('person_term',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_term_person_id'), 'person_term', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_term_term_id'), 'person_term', ['term_id'], unique=False)
    op.create_table('physical_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('identifier_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('identifier_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition_term_id', sa.Uuid(), nullable=True),
    sa.Column('dimensions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight_grams', sa.Float(), nullable=True),
    sa.Column('manufactured_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['condition_term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_asset_asset_id'), 'physical_asset', ['asset_id'], unique=True)
    op.create_table('raven_question',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('import_row_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_row.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['import_job.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raven_question_owner_id'), 'raven_question', ['owner_id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_term_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_cycle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_cycle_days', sa.Integer(), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('trial_ends_on', sa.Date(), nullable=True),
    sa.Column('cancelled_on', sa.Date(), nullable=True),
    sa.Column('auto_renews', sa.Boolean(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['category_term_id'], ['term.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_owner_id'), 'subscription', ['owner_id'], unique=False)
    op.create_table('tracked_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('record_type_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('billing_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_renews', sa.Boolean(), nullable=False),
    sa.Column('coverage_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['record_type_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_record_owner_id'), 'tracked_record', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tracked_record_record_type_id'), 'tracked_record', ['record_type_id'], unique=False)
    op.create_table('bill_payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('paid_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_payment_owner_id'), 'bill_payment', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bill_payment_subscription_id'), 'bill_payment', ['subscription_id'], unique=False)
    op.create_table('communication',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('sender_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recipient_identifiers', sa.JSON(), nullable=True),
    sa.Column('source_app', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('communicated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('interaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_owner_id'), 'communication', ['owner_id'], unique=False)
    op.create_table('digital_asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_asset_asset_id'), 'digital_asset', ['asset_id'], unique=True)
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    op.create_table('person_followup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('interaction_id', sa.Uuid(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_followup_owner_id'), 'person_followup', ['owner_id'], unique=False)
    op.create_index(op.f('ix_person_followup_person_id'), 'person_followup', ['person_id'], unique=False)
    op.create_table('person_observation_tag',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['person_observation.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('observation_id', 'term_id')
    )
    op.create_table('reminder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_asset_id'), 'reminder', ['asset_id'], unique=False)
    op.create_index(op.f('ix_reminder_owner_id'), 'reminder', ['owner_id'], unique=False)
    op.create_index(op.f('ix_reminder_person_id'), 'reminder', ['person_id'], unique=False)
    op.create_index(op.f('ix_reminder_subscription_id'), 'reminder', ['subscription_id'], unique=False)
    op.create_table('subscription_tag',
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'term_id')
    )
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_owner_id'), 'task', ['owner_id'], unique=False)
    op.create_table('note_tag',
    sa.Column('note_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('note_id', 'term_id')
    )
    op.create_table('task_tag',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'term_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_tag')
    op.drop_table('note_tag')
    op.drop_index(op.f('ix_task_owner_id'), table_name='task')
    op.drop_table('task')
    op.drop_table('subscription_tag')
    op.drop_index(op.f('ix_reminder_subscription_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_person_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_owner_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_asset_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_table('person_observation_tag')
    op.drop_index(op.f('ix_person_followup_person_id'), table_name='person_followup')
    op.drop_index(op.f('ix_person_followup_owner_id'), table_name='person_followup')
    op.drop_table('person_followup')
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_digital_asset_asset_id'), table_name='digital_asset')
    op.drop_table('digital_asset')
    op.drop_index(op.f('ix_communication_owner_id'), table_name='communication')
    op.drop_table('communication')
    op.drop_index(op.f('ix_bill_payment_subscription_id'), table_name='bill_payment')
    op.drop_index(op.f('ix_bill_payment_owner_id'), table_name='bill_payment')
    op.drop_table('bill_payment')
    op.drop_index(op.f('ix_tracked_record_record_type_id'), table_name='tracked_record')
    op.drop_index(op.f('ix_tracked_record_owner_id'), table_name='tracked_record')
    op.drop_table('tracked_record')
    op.drop_index(op.f('ix_subscription_owner_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_raven_question_owner_id'), table_name='raven_question')
    op.drop_table('raven_question')
    op.drop_index(op.f('ix_physical_asset_asset_id'), table_name='physical_asset')
    op.drop_table('physical_asset')
    op.drop_index(op.f('ix_person_term_term_id'), table_name='person_term')
    op.drop_index(op.f('ix_person_term_person_id'), table_name='person_term')
    op.drop_table('person_term')
    op.drop_table('person_tag')
    op.drop_index(op.f('ix_person_significant_date_person_id'), table_name='person_significant_date')
    op.drop_table('person_significant_date')
    op.drop_index(op.f('ix_person_relationship_to_person_id'), table_name='person_relationship')
    op.drop_index(op.f('ix_person_relationship_from_person_id'), table_name='person_relationship')
    op.drop_table('person_relationship')
    op.drop_index(op.f('ix_person_profile_person_id'), table_name='person_profile')
    op.drop_table('person_profile')
    op.drop_index(op.f('ix_person_professional_person_id'), table_name='person_professional')
    op.drop_table('person_professional')
    op.drop_index(op.f('ix_person_organization_person_id'), table_name='person_organization')
    op.drop_index(op.f('ix_person_organization_org_id'), table_name='person_organization')
    op.drop_table('person_organization')
    op.drop_index(op.f('ix_person_observation_person_id'), table_name='person_observation')
    op.drop_index(op.f('ix_person_observation_owner_id'), table_name='person_observation')
    op.drop_table('person_observation')
    op.drop_index(op.f('ix_person_location_person_id'), table_name='person_location')
    op.drop_table('person_location')
    op.drop_table('person_language')
    op.drop_index(op.f('ix_person_goal_person_id'), table_name='person_goal')
    op.drop_index(op.f('ix_person_goal_owner_id'), table_name='person_goal')
    op.drop_table('person_goal')
    op.drop_index(op.f('ix_person_context_person_id'), table_name='person_context')
    op.drop_table('person_context')
    op.drop_index(op.f('ix_person_channel_person_id'), table_name='person_channel')
    op.drop_table('person_channel')
    op.drop_index(op.f('ix_person_address_person_id'), table_name='person_address')
    op.drop_table('person_address')
    op.drop_index(op.f('ix_loan_person_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_owner_id'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_life_event_person_person_id'), table_name='life_event_person')
    op.drop_index(op.f('ix_life_event_person_life_event_id'), table_name='life_event_person')
    op.drop_table('life_event_person')
    op.drop_index(op.f('ix_interaction_person_id'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_owner_id'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_financial_asset_asset_id'), table_name='financial_asset')
    op.drop_table('financial_asset')
    op.drop_index(op.f('ix_event_person_person_id'), table_name='event_person')
    op.drop_index(op.f('ix_event_person_event_id'), table_name='event_person')
    op.drop_table('event_person')
    op.drop_index(op.f('ix_document_asset_asset_id'), table_name='document_asset')
    op.drop_table('document_asset')
    op.drop_table('asset_tag')
    op.drop_index(op.f('ix_asset_event_owner_id'), table_name='asset_event')
    op.drop_index(op.f('ix_asset_event_asset_id'), table_name='asset_event')
    op.drop_table('asset_event')
    op.drop_index(op.f('ix_person_owner_id'), table_name='person')
    op.drop_index(op.f('ix_person_household_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_organization_owner_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_household_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_life_event_owner_id'), table_name='life_event')
    op.drop_table('life_event')
    op.drop_index(op.f('ix_import_row_job_id'), table_name='import_row')
    op.drop_table('import_row')
    op.drop_index(op.f('ix_household_member_user_id'), table_name='household_member')
    op.drop_index(op.f('ix_household_member_household_id'), table_name='household_member')
    op.drop_table('household_member')
    op.drop_index(op.f('ix_event_owner_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_document_owner_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_contact_relationship_to_contact_id'), table_name='contact_relationship')
    op.drop_index(op.f('ix_contact_relationship_from_contact_id'), table_name='contact_relationship')
    op.drop_table('contact_relationship')
    op.drop_index(op.f('ix_asset_owner_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_timezone_name'), table_name='timezone')
    op.drop_table('timezone')
    op.drop_index(op.f('ix_term_vocabulary_id'), table_name='term')
    op.drop_index(op.f('ix_term_slug'), table_name='term')
    op.drop_table('term')
    op.drop_index(op.f('ix_import_job_owner_id'), table_name='import_job')
    op.drop_table('import_job')
    op.drop_index(op.f('ix_household_created_by'), table_name='household')
    op.drop_table('household')
    op.drop_index(op.f('ix_contact_owner_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_vocabulary_machine_name'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_raven_log_owner_id'), table_name='raven_log')
    op.drop_table('raven_log')
    op.drop_index(op.f('ix_language_iso_639_2'), table_name='language')
    op.drop_index(op.f('ix_language_iso_639_1'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_country_alpha3'), table_name='country')
    op.drop_index(op.f('ix_country_alpha2'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
